### PR TITLE
nRF52840 USBPhy Implementation

### PR DESCRIPTION
**Pull request by AGlass0fMilk**
### Description

Implemented USBPhy on the Nordic nRF52840 target.
- Added legacy driver files (`nrf_drv_usbd.*`)
- Pulled in new errata fixes and driver changes from Nordic SDK version 15.3
- Added implementation code for the USBPhy in `usb/device/targets/TARGET_NORDIC/...`

Extensive testing has been done and the basic USB test suite has passed hundreds of times. Admittedly, I have only been building with the `GCC_ARM` toolchain.

See comments on #7674 for test results

### Pull request type

    [ ] Fix
    [ ] Refactor
    [ X ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers

@TacoGrandeTX 
@c1728p9

### CODE REVIEW

**Comment by TacoGrandeTX** [comment]
@AGlass0fMilk With arm and gcc_arm builds I am getting a DeepSleepLock underflow (full log attached). 
```
[1552685312.18][CONN][RXD] >>> Running case #2: 'CDC RX single bytes'...
[1552685312.22][CONN][INF] found KV pair in stream: {{__testcase_start;CDC RX single bytes}}, queued...
[1552685312.25][CONN][INF] found KV pair in stream: {{send_single;0}}, queued...
[1552685312.88][CONN][RXD]
[1552685312.89][CONN][RXD]
[1552685312.92][CONN][RXD] ++ MbedOS Error Info ++
[1552685312.96][CONN][RXD] Error Status: 0x80040124 Code: 292 Module: 4
[1552685313.00][CONN][RXD] Error Message: DeepSleepLock underflow (< 0)
[1552685313.02][CONN][RXD] Location: 0x311B7
[1552685313.04][CONN][RXD] Error Value: 0x0
[1552685313.14][CONN][RXD] Current Thread: main  Id: 0x20007E50 Entry: 0x31699 StackSize: 0x1000 StackMem: 0x20008BD8 SP: 0x200096E8
[1552685313.25][CONN][RXD] For more info, visit: https://mbed.com/s/error?error=0x80040124&tgt=NRF52840_DK
[1552685313.25][CONN][RXD] -- MbedOS Error Info --
```
Have you seen this before? 

[gcc_results.txt](https://github.com/TacoGrandeTX/mbed-os/files/2973083/gcc_results.txt)

**Comment by TacoGrandeTX** [comment]
Woops - when I brought down your PR for local testing I missed your last commit.

**Comment by AGlass0fMilk** [comment]
@TacoGrandeTX I didn't run tests after I implemented the deep sleep lock code. I pretty much copied it over from when it was added into the other phy implementations

Are you still having issues running the tests?

**Comment by AGlass0fMilk** [comment]
@TacoGrandeTX The underflow was happening because I never set the `events` member variable to NULL.

The most recent commit should fix this. I ran the tests and they worked for me.

Let me know if you have any other issues.

**Comment by TacoGrandeTX** [comment]
@AGlass0fMilk Yesterday I brought in https://github.com/TacoGrandeTX/mbed-os/pull/10/commits/a42f62aa3142f5454a05091c1d60c7d0bf16f872 and device-serial tests are passing.  However, the basic tests are not - for either gcc or arm (Arm Compiler 6).  Attached is the overall output and verbose output for the basic tests.  It appears to hang when running "usb control basic test". 

[ac6_results.txt](https://github.com/TacoGrandeTX/mbed-os/files/3010759/ac6_results.txt)
[device-basic_verboseoutput.txt](https://github.com/TacoGrandeTX/mbed-os/files/3010760/device-basic_verboseoutput.txt)

**Comment by AGlass0fMilk** [comment]
@TacoGrandeTX That seems fishy. I have not had any issues with the control tests since January. 

I went through most of the dependencies and pip packages in that list and made a new python environment with your same version (`2.7.16`). I then installed the required packages to run the tests. I didn't see any hang. See results below:

[gcc_arm_results-htrun-1-5-3.txt](https://github.com/TacoGrandeTX/mbed-os/files/3013566/gcc_arm_results-htrun-1-5-3.txt)

My configuration is:
Python version 2.7.16
Ubuntu 18.04LTS kernel 4.15.0-43-generic
Compiling with GCC ARM 2017-q2-update
I have the DUT plugged directly into a USB port on my laptop.

I'll try testing on Windows and see if I encounter any issues.

**Comment by AGlass0fMilk** [comment]
@TacoGrandeTX 
Can you try rerunning the tests? I set up every the same on Windows (Python2.7.16, newest mbed-os-tools & related packages) and ran the basic tests. The only issue I encountered was in the final test (endpoint test data toggle reset) and I just added a commit (83ead94) that addressed the cause of that failure.

It's working on my system. Are these tests being run on mbed's automated CI or your local machine?

I had issues where the zadig config wasn't applying the libusb driver to the correct USB device VID/PID.

Here's the output from my tests on windows:
[windows-basic-test.txt](https://github.com/TacoGrandeTX/mbed-os/files/3014098/windows-basic-test.txt)

**Comment by TacoGrandeTX** [comment]
@AGlass0fMilk I've applied your last commit but still not working (same hang point as before). I'm on a ThinkPad Windows 10 laptop and it appears the driver isn't loading properly as Device Manager shows MBED_TEST_DEVICE under "Other devices".  Will diagnose and check this on another system.

**Comment by AGlass0fMilk** [comment]
Just to be sure, did you make sure to use the zadig utility mentioned in the usb basic readme to install the libusb driver for the MBED TEST DEVICE VID/PID combination?

I was having similar issues until I manually entered the VID/PID shown in device manager and replaced the existing windows driver with the libusb driver.

It appears the zadig config for that device is incorrect or something.

**Comment by TacoGrandeTX** [comment]
@AGlass0fMilk wrote:
> I was having similar issues until I manually entered the VID/PID shown in device
> manager and replaced the existing windows driver with the libusb driver.

Yes - that helped!  Along with removing an Mbed Serial Driver that was not needed on Windows10.  The basic tests are now also passing. I've tested with all 3 compilers (AC v6, GCC v6 and IAR v8.32) and they all pass... so great work! 
Let me consult with @c1728p9 if there is something else we need to look at.

**Comment by AGlass0fMilk** [comment]
@TacoGrandeTX Glad that worked out for you!

Any update on when this may be merged in?

**Comment by loverdeg-ep** [comment]
@maclobdell

**Pull request closed without merging**
